development:
  adapter: async

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>/1
  channel_prefix: backend_staging

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>/1
  channel_prefix: backend_production
