postgres: &postgres
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: pnikrat

development:
  <<: *postgres
  database: magisterka_development

test:
  <<: *postgres
  database: magisterka_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
